version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cane-ecommerce-dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules